import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { directDependencies, discoverTargets } from '../dist/upgrade/scan.js';

describe('Python source and compiled requirements flow', () => {
  test('discovers, resolves, selects, and rewrites the authoritative .in source', async () => {
    const source = [
      'pydantic>=2.0',
      'sphinx>=8.0',
      '',
    ].join('\n');
    const compiled = [
      '# This file was autogenerated by uv via the following command:',
      '#    uv pip compile docs/requirements.in -o docs/requirements.txt',
      'annotated-types==0.7.0',
      '    # via pydantic',
      'hpack==4.1.0',
      '    # via hyperframe',
      'pydantic==2.10.6',
      '    # via -r requirements.in',
      'pydantic-core==2.27.2',
      '    # via pydantic',
      'snowballstemmer==2.2.0',
      '    # via sphinx',
      'sphinx==8.2.3',
      '    # via -r requirements.in',
      'typing-inspection==0.4.0',
      '    # via pydantic',
      '',
    ].join('\n');
    const files = new Map([
      ['/repo/docs/requirements.in', source],
      ['/repo/docs/requirements.txt', compiled],
    ]);
    const fs = {
      readFile: async (path: string) => files.get(path) ?? null,
      readDirectory: async (path: string) => path === '/repo/docs' ? ['requirements.txt', 'requirements.in'] : [],
      isDirectory: async () => false,
    };

    const { targets } = await discoverTargets('/repo', ['docs'], new Map(), fs);
    assert.equal(targets.length, 1);
    assert.equal(targets[0]?.manifestPath, 'docs/requirements.in');
    assert.equal(targets[0]?.lockfilePath, 'docs/requirements.txt');

    const dependencies = await directDependencies('/repo', targets[0]!, false, fs);
    assert.deepEqual(dependencies.map((dependency) => dependency.name).sort(), ['pydantic', 'sphinx']);
    assert.equal(dependencies.find((dependency) => dependency.name === 'pydantic')?.current, '2.10.6');
    for (const transitive of ['annotated-types', 'hpack', 'pydantic-core', 'snowballstemmer', 'typing-inspection']) {
      assert.equal(dependencies.some((dependency) => dependency.name === transitive), false);
    }

    const rewritten = targets[0]!.manager.rewriteManifest!(
      source,
      { name: 'pydantic', version: '2.11.0', kind: 'runtime' },
      targets[0]!.manifestPath,
    );
    assert.match(rewritten, /^pydantic==2\.11\.0$/m);
    assert.equal(compiled.includes('pydantic-core==2.27.2'), true, 'generated transitive output remains untouched');
  });
});
