import { test, describe, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { looksGenerated, walkSourceFiles } from '../dist/index/walk.js';

/**
 * One committed bundle used to invalidate a whole repository.
 *
 * `localizationComplete` was `indexed === discovered`, so any file too large to
 * read made the answer `false` — and a `false` there downgrades *every*
 * dependency to "absence of local use was not proved". On Drift's own
 * repository a single 1.8 MB `action/index.cjs`, one file of 1,584, put fifteen
 * of eighteen upgrades into that bucket: a wall of shrugs on the first run
 * anyone would do.
 *
 * The distinction that fixes it is real rather than convenient. A bundle holds
 * every dependency inlined and minified; a match inside one is not a place
 * anyone edits, and its absence proves nothing about the source that produced
 * it. Skipping it is not a gap. Skipping genuine source still is, and the two
 * are counted separately so the report can keep saying which.
 */

let dirs: string[] = [];

async function repo(files: Record<string, string>): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), 'drift-walk-generated-'));
  dirs.push(root);
  for (const [path, content] of Object.entries(files)) {
    const full = join(root, path);
    await mkdir(join(full, '..'), { recursive: true });
    await writeFile(full, content);
  }
  return root;
}

afterEach(async () => {
  await Promise.all(dirs.map((dir) => rm(dir, { recursive: true, force: true })));
  dirs = [];
});

/** Bigger than the walker's 512 KB ceiling, on one line, the way a bundler emits. */
const MINIFIED = `(()=>{${'var a=1;'.repeat(90_000)}})();`;
/** Equally oversized, but written the way a person writes. */
const HANDWRITTEN = `${'export const value = 1;\n'.repeat(30_000)}`;

describe('deciding what an unread file means', () => {
  test('a committed bundle does not make the repository incomplete', async () => {
    const root = await repo({
      'src/app.ts': `import { createClient } from 'acme';\ncreateClient();\n`,
      'action/index.cjs': MINIFIED,
    });

    const files = await walkSourceFiles(root);
    const { coverage } = files;

    assert.equal(coverage.generatedFilesSkipped, 1, 'the bundle was recognised');
    assert.equal(coverage.oversizedSourceSkipped, 0);
    assert.equal(coverage.localizationComplete, true, 'and skipping it is not a gap');
    assert.equal(coverage.sourceTruncated, false);
    assert.ok(files.some((file) => file.path === 'src/app.ts'), 'real source is still indexed');
    assert.ok(!files.some((file) => file.path === 'action/index.cjs'), 'the bundle is not');
  });

  test('oversized handwritten source is still a gap', async () => {
    const root = await repo({
      'src/app.ts': 'export const a = 1;\n',
      'src/enormous.ts': HANDWRITTEN,
    });

    const { coverage } = await walkSourceFiles(root);
    assert.equal(coverage.generatedFilesSkipped, 0, 'nothing here announces itself as generated');
    assert.equal(coverage.oversizedSourceSkipped, 1);
    assert.equal(coverage.localizationComplete, false, 'there may be something here Drift did not read');
    assert.equal(coverage.sourceTruncated, true);
  });

  test('a repository with nothing oversized is complete and says so', async () => {
    const root = await repo({ 'src/a.ts': 'export const a = 1;\n', 'src/b.ts': 'export const b = 2;\n' });
    const { coverage } = await walkSourceFiles(root);
    assert.deepEqual(
      {
        complete: coverage.localizationComplete,
        generated: coverage.generatedFilesSkipped,
        oversized: coverage.oversizedSourceSkipped,
      },
      { complete: true, generated: 0, oversized: 0 },
    );
  });
});

describe('recognising build output', () => {
  test('a single enormous line is minified output', async () => {
    const root = await repo({ 'bundle.js': MINIFIED });
    assert.equal(await looksGenerated(join(root, 'bundle.js')), true);
  });

  test('a self-declared banner is enough on its own', async () => {
    for (const banner of ['// @generated by protoc', '/* eslint-disable */\n// DO NOT EDIT', '// Code generated by mockgen.']) {
      const root = await repo({ 'g.ts': `${banner}\n${'export const x = 1;\n'.repeat(50)}` });
      assert.equal(await looksGenerated(join(root, 'g.ts')), true, banner);
    }
  });

  test('ordinary source is never mistaken for build output', async () => {
    const root = await repo({
      'src/normal.ts': HANDWRITTEN,
      'src/licensed.ts': `/*\n * Copyright 2026. Licensed under Apache-2.0.\n */\n${'export const a = 1;\n'.repeat(200)}`,
    });
    assert.equal(await looksGenerated(join(root, 'src/normal.ts')), false);
    assert.equal(await looksGenerated(join(root, 'src/licensed.ts')), false);
  });

  test('a file that cannot be read is treated as source, not as build output', async () => {
    const root = await repo({});
    // Wrong in the safe direction: an unclassifiable file counts as a gap, so
    // Drift under-claims coverage rather than over-claiming it.
    assert.equal(await looksGenerated(join(root, 'does-not-exist.js')), false);
  });
});
