import { test } from "node:test";
import assert from "node:assert/strict";
import { deriveStatus, excerptFromBody, normalizeFeature, normalizeFeatures, readFeatureCache, sortNew, sortShipped, sortTop, writeFeatureCache, type Feature } from "./github-features.ts";

const issue = (extra: Record<string, unknown> = {}) => ({ number: 1, title: "A feature", body: "## Problem\n\n**Make it better**", html_url: "https://github.com/trydrift/drift/issues/1", state: "open", created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-02T00:00:00Z", closed_at: null, comments: 2, labels: [{ name: "feature-request" }], reactions: { "+1": 7, heart: 99 }, ...extra });
test("excludes pull requests and unlabeled issues", () => { assert.equal(normalizeFeature(issue({ pull_request: {} })), null); assert.equal(normalizeFeature(issue({ labels: [] })), null); });
test("uses only +1 reactions and handles missing summaries", () => { assert.equal(normalizeFeature(issue())?.votes, 7); assert.equal(normalizeFeature(issue({ reactions: null }))?.votes, 0); });
test("status precedence and view sorting work", () => { assert.equal(deriveStatus("open", ["status: planned", "status: shipped"]), "Shipped"); const make = (n: number, votes: number, created: string, status: Feature["status"] = "Requested"): Feature => ({ number: n, title: String(n), excerpt: "", htmlUrl: "", state: status === "Closed" ? "closed" : "open", status, votes, comments: 0, createdAt: created, updatedAt: created, closedAt: null }); const xs = [make(1, 2, "2026-01-01T00:00:00Z"), make(2, 2, "2026-01-02T00:00:00Z"), make(3, 9, "2025-01-01T00:00:00Z"), make(4, 1, "2026-01-03T00:00:00Z", "Closed"), make(5, 1, "2026-01-03T00:00:00Z", "Shipped")]; assert.deepEqual(sortTop(xs).map((f) => f.number), [3, 2, 1]); assert.deepEqual(sortNew(xs).map((f) => f.number), [2, 1, 3]); assert.deepEqual(sortShipped(xs).map((f) => f.number), [5]); });
test("normalizes issue-form markdown to safe text and handles null", () => { assert.equal(excerptFromBody("## Problem\n\n[Read](https://evil.test) **text**\n\n- more"), "Problem Read text"); assert.equal(excerptFromBody(null), ""); });
test("ignores malformed entries and validates cache", () => { assert.deepEqual(normalizeFeatures([null, {}, issue({ number: "bad" })]), []); const feature = normalizeFeature(issue())!; const raw = writeFeatureCache([feature], 1000); assert.equal(readFeatureCache(raw, 1000 + 100)?.length, 1); assert.equal(readFeatureCache(raw, 1000 + 6 * 60 * 1000), null); assert.equal(readFeatureCache(JSON.stringify({ schema: 99, cachedAt: 1000, features: [] }), 1000), null); });
