/** Shared recognition for pip requirements/constraints source and output files. */
export function isPythonRequirementsFile(path: string): boolean {
  const base = path.replace(/\\/g, '/').split('/').at(-1) ?? '';
  return /^(?:requirements|constraints)[\w.-]*\.(?:in|txt)$/i.test(base);
}

export function isPythonRequirementsInputFile(path: string): boolean {
  return isPythonRequirementsFile(path) && /\.in$/i.test(path);
}

export function isCompiledPythonRequirements(content: string): boolean {
  return /(?:autogenerated|generated) by (?:uv(?: pip compile)?|pip-compile)|uv pip compile/i.test(
    content.split('\n').slice(0, 20).join('\n'),
  );
}
