import type { Ecosystem } from '../../types.js';
import { readArchive } from '../../util/archive.js';
import { fetchArchive, fetchJson, fetchText } from '../../util/http.js';
import { arduinoLibrary } from '../arduino-index.js';
import { fetchRegistryInfo, parseGitHubRepo } from '../registry.js';
import { diffSurfaces, type SurfaceApi } from '../type-surface.js';
import { publicHeaders, parseHeaderSurface, type HeaderFile } from './c-headers.js';
import { unavailable, type SurfaceOutcome, type SurfaceProvider, type SurfaceRequest } from './types.js';

/**
 * Header diffing for C and C++, across all three of their package managers.
 *
 * One provider serves Conan, vcpkg, and Arduino because the comparison is
 * identical in all three — parse both versions' public headers, diff the
 * declarations — and only the question *where do I get version X's source?*
 * differs. That question is answered by `SOURCES` below, one small function per
 * ecosystem, and nothing downstream of it knows which one ran.
 *
 * Nothing is installed, unpacked to disk, or built. Two archives are fetched,
 * read in memory (`util/archive.ts`), and the headers inside them parsed. That
 * is a stronger position than any other non-npm provider Drift has: no
 * toolchain to be missing, no build to fail, and no third-party build script
 * executed to find out what a library declares.
 *
 * The one honest limit is `#ifdef`, and it is stated everywhere this provider's
 * output is shown. See `c-headers.ts`.
 */

const TOOL = 'header diff';

/**
 * One notch below a compiled diff, and above prose.
 *
 * Deliberately equal to the Python provider's, which puts a lone C surface
 * diff at `medium` confidence in `analyze`. Headers are the real published
 * interface rather than a reconstruction of one — which argues for more — but
 * the preprocessor is genuinely invisible here, and a declaration Drift reads
 * as present may compile away on the consumer's platform. Corroboration from a
 * changelog promotes it, which is the correct way for it to reach `high`.
 */
const WEIGHT = 0.9;

/** Where one version's source archive lives, per ecosystem. */
type SourceResolver = (name: string, version: string) => Promise<string | null>;

const SOURCES: Partial<Record<Ecosystem, SourceResolver>> = {
  arduino: arduinoArchive,
  conan: conanArchive,
  vcpkg: vcpkgArchive,
};

function providerFor(ecosystem: Ecosystem): SurfaceProvider {
  return {
    ecosystem,
    tool: TOOL,
    weight: WEIGHT,
    compute: (request) => compute(ecosystem, request),
  };
}

export const arduinoSurface = providerFor('arduino');
export const conanSurface = providerFor('conan');
export const vcpkgSurface = providerFor('vcpkg');

async function compute(ecosystem: Ecosystem, request: SurfaceRequest): Promise<SurfaceOutcome> {
  const resolve = SOURCES[ecosystem];
  if (!resolve) {
    return unavailable(TOOL, 'unsupported-ecosystem', `No source resolver for ${ecosystem}.`);
  }

  const beforePromise = surfaceOf(ecosystem, resolve, request, request.from);
  const afterPromise = surfaceOf(ecosystem, resolve, request, request.to);
  afterPromise.catch(() => undefined);
  const before = await beforePromise;
  if (!before.ok) return before.failure;
  const after = await afterPromise;
  if (!after.ok) return after.failure;

  // Both versions parsed and neither declared anything. That is a fact about
  // the library — a macro-generated API, or a distribution that ships only
  // binaries — and reporting it as a clean comparison would be a claim that
  // nothing broke, which nothing here established.
  if (before.api.size === 0 && after.api.size === 0) {
    return unavailable(
      TOOL,
      'no-public-surface',
      `No declarations could be read from ${request.name}'s headers in either version. A library whose API is generated by macros, or shipped as a prebuilt binary, has no header text to compare.`,
    );
  }

  return {
    available: true,
    changes: diffSurfaces(before.api, after.api),
    tool: TOOL,
    weight: WEIGHT,
    locator: `${request.name} ${request.from} → ${request.to} (public headers)`,
  };
}

type Attempt = { ok: true; api: SurfaceApi } | { ok: false; failure: SurfaceOutcome };

async function surfaceOf(
  ecosystem: Ecosystem,
  resolve: SourceResolver,
  request: SurfaceRequest,
  version: string,
): Promise<Attempt> {
  const url = await resolve(request.name, version);
  if (!url) {
    return {
      ok: false,
      failure: unavailable(
        TOOL,
        'version-unavailable',
        `No source archive is published for ${request.name} ${version} in ${registryName(ecosystem)}, so its headers could not be read.`,
      ),
    };
  }

  let files: HeaderFile[];
  try {
    const downloaded = await fetchArchive(url, { timeoutMs: request.timeoutMs });
    // A request that never completed used to throw out of `fetch`; re-thrown so
    // it still lands in this provider's own catch, with the same message.
    if (!downloaded.ok && downloaded.status === 0) throw new Error(downloaded.error ?? 'the request failed');
    if (!downloaded.ok) {
      return {
        ok: false,
        failure: unavailable(TOOL, 'version-unavailable', `${url} returned ${downloaded.status}.`),
      };
    }

    const entries = readArchive(downloaded.bytes);
    const byPath = new Map(entries.map((entry) => [entry.path, entry]));
    files = publicHeaders([...byPath.keys()])
      .map((header) => ({
        path: header.path,
        content: byPath.get(header.original)!.read().toString('utf8'),
      }))
      .filter((file): file is HeaderFile => file.content.length > 0);
  } catch (err) {
    return {
      ok: false,
      failure: unavailable(
        TOOL,
        'toolchain-failed',
        `Could not read ${request.name} ${version} from ${url}: ${(err as Error).message}`,
      ),
    };
  }

  request.logger.debug(`${request.name} ${version}: ${files.length} public header(s)`);
  return { ok: true, api: parseHeaderSurface(files) };
}

function registryName(ecosystem: Ecosystem): string {
  if (ecosystem === 'conan') return 'ConanCenter';
  if (ecosystem === 'vcpkg') return 'the vcpkg registry';
  return 'the Arduino Library Manager';
}

/* ---------------- per-ecosystem source resolution ---------------- */

/**
 * The Library Manager index records an exact archive URL per release.
 *
 * When it does not, the upstream repository still does. Two large groups of
 * libraries land here and both are ordinary rather than exotic: those published
 * only to PlatformIO (`lib_deps` is full of them — `AsyncMqttClient-esphome`,
 * `HaierProtocol`), and those in the index at a *different* version than the
 * one a project pins, since a project's installed version is frequently older
 * than anything the index still lists.
 *
 * Before this fallback those were reported as "not verified" while their tags,
 * their sources, and their release notes sat one request away on GitHub — which
 * is not a limit of what can be known, only of where Drift had looked.
 */
async function arduinoArchive(name: string, version: string): Promise<string | null> {
  const library = await arduinoLibrary(name);
  const published = library?.archives[version];
  if (published) return published;

  const repo = library?.githubRepo ?? (await arduinoRepo(name));
  return repo ? githubTagArchive(repo, version) : null;
}

/**
 * The upstream repository of a library the Arduino index does not carry.
 *
 * Goes through `fetchRegistryInfo` rather than PlatformIO directly so that the
 * one place that knows how to find an Arduino library's repository stays the
 * one place — including the search-then-fetch dance PlatformIO's API requires.
 */
async function arduinoRepo(name: string): Promise<string | null> {
  const info = await fetchRegistryInfo(name, 'arduino', null);
  return info?.githubRepo ?? null;
}

/**
 * ConanCenter's `conandata.yml`, which names the upstream source per version.
 *
 * This is the recipe's own record of where the library came from, so what gets
 * compared is the library rather than the packaging around it. Recipes list
 * several mirrors for one version; the first that is a plain archive is taken,
 * and a `git` source (rare, and used for libraries with no release tarballs)
 * is skipped rather than shallow-cloned.
 */
async function conanArchive(name: string, version: string): Promise<string | null> {
  const base = `https://raw.githubusercontent.com/conan-io/conan-center-index/master/recipes/${encodeURIComponent(name)}`;
  const config = await fetchText(`${base}/config.yml`);
  if (!config) return null;

  const folder = folderForVersion(config, version) ?? anyFolder(config);
  if (!folder) return null;

  const conandata = await fetchText(`${base}/${folder}/conandata.yml`);
  if (!conandata) return null;

  const exact = sourceUrlForVersion(conandata, version);
  if (exact) return exact;

  // ConanCenter prunes old versions from its recipes: zlib's `config.yml`
  // lists one version, not the eleven that exist. So the version a project has
  // *installed* — which is the whole left-hand side of the comparison — is
  // usually absent from the index that knows about the right-hand side.
  //
  // The recipe still names the upstream project, and the upstream project
  // still has the tag. Falling back to it is what makes a Conan surface diff
  // possible at all for anything but a repository already on the newest
  // version, where there would be nothing to compare.
  const upstream = firstGitHubRepo(conandata);
  return upstream ? githubTagArchive(upstream, version) : null;
}

/** Any recipe folder, for a version the index no longer lists. */
function anyFolder(config: string): string | null {
  return /folder\s*:\s*["']?([^"'\s]+)["']?/.exec(config)?.[1] ?? null;
}

function firstGitHubRepo(content: string): string | null {
  for (const match of content.matchAll(/https?:\/\/github\.com\/[\w.-]+\/[\w.-]+/g)) {
    const repo = parseGitHubRepo(match[0]);
    if (repo) return repo;
  }
  return null;
}

/**
 * A source archive for one version, from the upstream repository's tags.
 *
 * Tag spellings are not standardised — `v1.3.1`, `1.3.1`, `zlib-1.3.1`, and
 * `release_1_3_1` all appear in projects Drift will meet — so the tag list is
 * fetched and matched rather than a URL being constructed from a guess. One
 * request, cached, and a miss is reported rather than papered over.
 */
async function githubTagArchive(repo: string, version: string): Promise<string | null> {
  const tags = await fetchJson<{ name?: string }[]>(
    `https://api.github.com/repos/${repo}/tags?per_page=100`,
  );

  const tag = (tags ?? [])
    .map((entry) => entry.name)
    .find((candidate): candidate is string => Boolean(candidate) && matchesVersion(candidate!, version));

  return tag ? `https://codeload.github.com/${repo}/tar.gz/refs/tags/${encodeURIComponent(tag)}` : null;
}

/** Which recipe folder builds this version, from `config.yml`. */
export function folderForVersion(config: string, version: string): string | null {
  const lines = config.split('\n');
  let current: string | null = null;

  for (const line of lines) {
    const key = /^\s{2,}["']?([^"':\s]+)["']?\s*:\s*$/.exec(line.replace(/\s+$/, ''));
    if (key) {
      current = key[1]!.trim();
      continue;
    }
    const folder = /^\s{4,}folder\s*:\s*["']?([^"'\s]+)["']?/.exec(line);
    if (folder && current === version) return folder[1]!;
  }

  return null;
}

/**
 * The archive URL for one version in `conandata.yml`.
 *
 * Read by indentation rather than with a YAML parser, for the same reason
 * `parseConanConfig` is: the version keys are quoted numbers, and a
 * general-purpose parser hands back `1.3` for `"1.3.0"`.
 */
export function sourceUrlForVersion(conandata: string, version: string): string | null {
  const lines = conandata.split('\n');
  let inSources = false;
  let inVersion = false;

  for (const rawLine of lines) {
    const line = rawLine.replace(/\s+$/, '');
    if (!line.trim()) continue;

    if (/^sources\s*:/.test(line)) {
      inSources = true;
      continue;
    }
    if (!/^\s/.test(line)) {
      inSources = false;
      inVersion = false;
      continue;
    }
    if (!inSources) continue;

    // The capture forbids whitespace so that a nested `    url:` — which is
    // also two-or-more spaces followed by a colon — is not read as another
    // version key, silently ending the version whose URL it holds.
    const key = /^ {2}["']?([^"':\s]+)["']?\s*:\s*$/.exec(line);
    if (key) {
      inVersion = key[1]!.trim() === version;
      continue;
    }
    if (!inVersion) continue;

    const url = /https?:\/\/\S+/.exec(line);
    if (url && !url[0].endsWith('.git')) return url[0].replace(/["',]+$/, '');
  }

  return null;
}

/**
 * A vcpkg port's source, via the upstream project's GitHub release.
 *
 * The port's own recipe is `portfile.cmake` — a CMake program whose source URL
 * is assembled from variables, and evaluating CMake to find out is not
 * something Drift does. So the upstream repository from the port manifest is
 * asked instead, and its tags are matched against the version.
 *
 * That is a resolution step the other two do not need, and it fails more often
 * than they do: a port whose homepage is a project page rather than a
 * repository has nothing to ask. The failure is reported as
 * `version-unavailable` with the reason, and the upgrade falls back to prose
 * evidence — which is the correct outcome and, importantly, a stated one.
 */
async function vcpkgArchive(name: string, version: string): Promise<string | null> {
  const port = await fetchJson<{ homepage?: string }>(
    `https://raw.githubusercontent.com/microsoft/vcpkg/master/ports/${encodeURIComponent(name)}/vcpkg.json`,
  );
  const repo = parseGitHubRepo(port?.homepage ?? null);
  return repo ? githubTagArchive(repo, version) : null;
}

/** `v1.3.1`, `1.3.1`, `release-1.3.1`, `zlib-1.3.1` all name version 1.3.1. */
export function matchesVersion(tag: string, version: string): boolean {
  const normalize = (value: string): string => value.replace(/^[^\d]*/, '').replace(/_/g, '.');
  return tag === version || normalize(tag) === normalize(version);
}
