import {
  CAPABILITY_STAGES,
  ECOSYSTEM_CAPABILITIES,
  STAGE_LABEL,
  type EcosystemCapability,
  type SupportLevel,
} from '../detect/capabilities.js';

/**
 * The support matrix, rendered from the capability data.
 *
 * `docs/support.md` is generated by `npm run docs:support` and checked in, and
 * a test asserts the checked-in file matches what this produces. That is the
 * whole point: a support table maintained by hand is a claim that decays
 * silently, and the decay always runs in the flattering direction — nobody
 * ever forgets to delete a capability they lost.
 */

const MARK: Record<SupportLevel, string> = {
  full: 'Yes',
  partial: 'Partial',
  none: 'No',
};

export function renderSupportMatrix(): string {
  const lines: string[] = [];

  lines.push('<!--');
  lines.push('  Generated by `npm run docs:support` from src/detect/capabilities.ts.');
  lines.push('  Do not edit by hand — a test asserts this file matches the code.');
  lines.push('-->');
  lines.push('');
  lines.push('# What Drift supports');
  lines.push('');
  lines.push('Every row is what the code actually does today. `Partial` is the common case and');
  lines.push(
    'always carries a reason underneath — a stage marked partial does something real and',
  );
  lines.push('does not do something else, and which is which is the part worth knowing.');
  lines.push('');
  lines.push(
    'The distinction this table exists to preserve: **"Drift cannot check this here" and',
  );
  lines.push('"Drift checked and found nothing" are different facts, and only one of them is');
  lines.push('reassuring.** Drift never renders the first as the second.');
  lines.push('');

  lines.push('## What the stages mean');
  lines.push('');
  lines.push('| Stage | Meaning |');
  lines.push('| --- | --- |');
  for (const stage of CAPABILITY_STAGES) {
    lines.push(`| ${STAGE_LABEL[stage]} | ${STAGE_MEANING[stage]} |`);
  }
  lines.push('');

  lines.push('## The matrix');
  lines.push('');
  lines.push(`| Ecosystem | ${CAPABILITY_STAGES.map((s) => STAGE_LABEL[s]).join(' | ')} |`);
  lines.push(`| --- | ${CAPABILITY_STAGES.map(() => '---').join(' | ')} |`);
  for (const capability of ECOSYSTEM_CAPABILITIES) {
    const cells = CAPABILITY_STAGES.map((stage) => MARK[capability.support[stage].level]);
    lines.push(`| ${capability.label} | ${cells.join(' | ')} |`);
  }
  lines.push('');

  for (const capability of ECOSYSTEM_CAPABILITIES) {
    lines.push(...renderEcosystem(capability));
  }

  lines.push('## Ecosystems that are not on this list');
  lines.push('');
  lines.push(
    '**Scala** is supported, through `maven`. sbt coordinates resolve to Maven Central',
  );
  lines.push(
    'artifacts, so `build.sbt` is parsed into the Maven ecosystem and inherits its',
  );
  lines.push(
    'registry lookups, its japicmp surface diff, and its OSV advisories. Drift applies',
  );
  lines.push(
    "the Scala binary-version suffix the way sbt does, so `\"org\" %% \"cats-core\"` is",
  );
  lines.push('resolved as `cats-core_2.13` rather than as an artifact that has never existed.');
  lines.push('');
  lines.push(
    '**React Native** is supported, as two ecosystems. Its JavaScript half is `npm` and',
  );
  lines.push(
    'its native iOS half is `cocoapods`. This matters more than it sounds: a React Native',
  );
  lines.push(
    'upgrade routinely moves native pods underneath the JavaScript package, and a tool',
  );
  lines.push('that reads only `package.json` reports half the change as though it were all of it.');
  lines.push('');

  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n')}\n`;
}

function renderEcosystem(capability: EcosystemCapability): string[] {
  const lines: string[] = [];

  lines.push(`## ${capability.label}`);
  lines.push('');
  lines.push(`**Files:** ${capability.files.map((f) => `\`${f}\``).join(', ')}`);
  lines.push('');
  lines.push(`**Package managers:** ${capability.managers.join(', ')}`);
  lines.push('');

  for (const stage of CAPABILITY_STAGES) {
    const support = capability.support[stage];
    if (support.level === 'full') continue;

    const requires = support.requires ? ` *Requires ${support.requires}.*` : '';
    lines.push(`- **${STAGE_LABEL[stage]} — ${MARK[support.level]}.** ${support.note ?? ''}${requires}`);
  }

  const everythingFull = CAPABILITY_STAGES.every((s) => capability.support[s].level === 'full');
  if (everythingFull) lines.push('- Every stage is fully supported.');

  lines.push('');
  return lines;
}

const STAGE_MEANING: Record<(typeof CAPABILITY_STAGES)[number], string> = {
  detect: 'Drift finds manifests, lockfiles, and the dependency versions that moved.',
  evidence: 'Drift retrieves and normalises release, changelog, advisory, and registry evidence.',
  surface: 'Drift compares the published API of the two versions.',
  'static-analysis': 'Drift identifies likely affected source references in your repository.',
  verify: "Drift runs the ecosystem's own typecheck, test, and build commands.",
  fix: 'Drift produces scoped changes.',
  'pull-request': 'Drift can branch, validate, commit, push, and open a pull request.',
};
