import type { DependencyKind } from '../../types.js';
import { basename, type DependencyMap, type ManifestParser } from './types.js';

/**
 * OCaml — `*.opam`, `dune-project`, and `*.opam.locked`.
 *
 * opam's `depends:` field is a list whose elements are either a bare package
 * name or a name followed by a constraint formula:
 *
 *   depends: [
 *     "ocaml" {>= "4.14"}
 *     "dune" {>= "3.0" & build}
 *     "alcotest" {with-test}
 *   ]
 *
 * The braces carry both version constraints and *filters* — `with-test`,
 * `with-doc`, `build`, `dev` — which is how opam spells a dev dependency. Both
 * live in the same expression, so they are read together rather than by two
 * passes that could disagree.
 */
export const opamParser: ManifestParser = {
  ecosystem: 'opam',
  name: 'opam',

  handles(path) {
    const base = basename(path);
    return base.endsWith('.opam') || base.endsWith('.opam.locked') || base === 'dune-project';
  },

  isLockfile(path) {
    return basename(path).endsWith('.opam.locked');
  },

  parse(content, path) {
    if (basename(path) === 'dune-project') return parseDuneProject(content);
    const lockfile = basename(path).endsWith('.opam.locked');
    return parseOpam(content, lockfile);
  },
};

/**
 * `dune-project`, which is where a modern OCaml project's dependencies live.
 *
 * A project with `(generate_opam_files true)` — the default for anything
 * created this decade — writes its `.opam` files from `dune-project` and
 * commits them with a "This file is generated by dune, edit dune-project
 * instead" header. `dune-project` is therefore read first, and it is not opam
 * syntax: it is s-expressions.
 *
 *   (package
 *    (name cohttp)
 *    (depends
 *     (ocaml (>= 4.08))
 *     uri
 *     (alcotest :with-test)))
 *
 * Reading it as opam syntax found nothing at all and reported it as a project
 * with no dependencies, which is the failure this whole file's sibling
 * `capabilities.ts` exists to make impossible to ship quietly. cohttp — twelve
 * opam packages, dozens of dependencies — analysed as one nested package.json.
 */
export function parseDuneProject(content: string): DependencyMap {
  const out: DependencyMap = new Map();

  for (const body of sexpBodies(content, 'depends')) {
    for (const entry of sexpEntries(body)) {
      // `(ocaml (>= 4.08))` or a bare `uri`.
      const named = /^\(\s*([\w.+-]+)([\s\S]*)\)$/.exec(entry);
      const name = named?.[1] ?? (/^[\w.+-]+$/.test(entry) ? entry : undefined);
      if (!name) continue;

      const rest = named?.[2] ?? '';
      const kind: DependencyKind = /:with-test|:with-doc|:dev/.test(rest) ? 'dev' : 'runtime';
      out.set(name, { version: duneVersionOf(rest), kind });
    }
  }

  return out;
}

/** `(>= 4.08)` -> `>= 4.08`; `(and (>= 1.0) (< 2.0))` -> `>= 1.0 & < 2.0`. */
function duneVersionOf(constraint: string): string | null {
  const comparisons = [...constraint.matchAll(/([<>=]+)\s*([\w.~+-]+)/g)].map(
    (m) => `${m[1]} ${m[2]}`,
  );
  if (comparisons.length === 0) return null;
  if (comparisons.length === 1 && comparisons[0]!.startsWith('= ')) {
    return comparisons[0]!.slice(2);
  }
  return comparisons.join(' & ');
}

/** The bodies of every `(field …)` s-expression in the document. */
function sexpBodies(content: string, field: string): string[] {
  const out: string[] = [];
  const opener = new RegExp(`\\(\\s*${field}\\b`, 'g');

  for (const match of content.matchAll(opener)) {
    let depth = 1;
    let i = match.index + match[0].length;
    const start = i;
    for (; i < content.length && depth > 0; i++) {
      const ch = content[i];
      if (ch === '(') depth += 1;
      else if (ch === ')') depth -= 1;
    }
    out.push(content.slice(start, i - 1));
  }

  return out;
}

/** Split a dune list into atoms and balanced parenthesised groups. */
function sexpEntries(body: string): string[] {
  const out: string[] = [];
  let current = '';
  let depth = 0;

  for (const ch of body) {
    if (ch === '(') depth += 1;
    else if (ch === ')') depth -= 1;

    if (depth === 0 && /\s/.test(ch)) {
      if (current.trim()) out.push(current.trim());
      current = '';
      continue;
    }
    current += ch;
  }

  if (current.trim()) out.push(current.trim());
  return out;
}

/** Fields that hold dependencies, and what a bare entry in them means. */
const DEPENDS_FIELDS: Record<string, DependencyKind> = {
  depends: 'runtime',
  depopts: 'optional',
};

function parseOpam(content: string, lockfile: boolean): DependencyMap {
  const out: DependencyMap = new Map();

  for (const [field, defaultKind] of Object.entries(DEPENDS_FIELDS)) {
    for (const body of listsOf(content, field)) {
      for (const entry of splitEntries(body)) {
        const name = /^"([^"]+)"/.exec(entry)?.[1];
        if (!name) continue;

        const constraint = /\{([\s\S]*)\}/.exec(entry)?.[1] ?? '';

        // A filter, not a version. `with-test` and `with-doc` mark a package
        // that is only pulled in for tests or docs.
        const kind: DependencyKind = /\bwith-test\b|\bwith-doc\b|\bdev\b/.test(constraint)
          ? 'dev'
          : defaultKind;

        out.set(name, {
          version: versionOf(constraint),
          // A `.locked` file is a resolved snapshot: every entry in it is a
          // fact about what was installed, which is the transitive set.
          kind: lockfile ? 'transitive' : kind,
        });
      }
    }
  }

  return out;
}

/**
 * The version a constraint formula pins.
 *
 * `{= "1.2.3"}` is an exact pin and the common case in a `.locked` file.
 * Anything else — `>= "4.14" & < "5.0"` — is kept verbatim as a range, since
 * that is what the manifest actually says and rewriting it would be a claim.
 * A formula with no version at all (`{build}`, `{with-test}`) yields `null`.
 */
function versionOf(constraint: string): string | null {
  if (!constraint.trim()) return null;

  const comparisons = [...constraint.matchAll(/([<>=!]+)\s*"([^"]+)"/g)].map(
    (m) => `${m[1]} ${m[2]}`,
  );
  if (comparisons.length === 0) return null;

  const exact = /^=\s/.exec(comparisons[0]!) && comparisons.length === 1;
  return exact ? comparisons[0]!.slice(2) : comparisons.join(' & ');
}

/** The bracketed bodies of every `field: [ … ]` in the document. */
function listsOf(content: string, field: string): string[] {
  const out: string[] = [];
  const opener = new RegExp(`(?:^|\\n)\\s*${field}\\s*:\\s*\\[`, 'g');

  for (const match of content.matchAll(opener)) {
    let depth = 1;
    let i = match.index + match[0].length;
    const start = i;
    for (; i < content.length && depth > 0; i++) {
      const ch = content[i];
      if (ch === '"') {
        // Skip the whole string, so a `]` inside one does not close the list.
        i += 1;
        while (i < content.length && content[i] !== '"') {
          if (content[i] === '\\') i += 1;
          i += 1;
        }
        continue;
      }
      if (ch === '[') depth += 1;
      else if (ch === ']') depth -= 1;
    }
    out.push(content.slice(start, i - 1));
  }

  return out;
}

/**
 * Split a `depends:` body into one entry per package.
 *
 * Entries are whitespace-separated, but a `{ … }` formula may contain spaces,
 * so the split has to respect brace depth rather than being a `.split(/\s+/)`.
 */
function splitEntries(body: string): string[] {
  const out: string[] = [];
  let current = '';
  let depth = 0;

  for (let i = 0; i < body.length; i++) {
    const ch = body[i]!;

    if (ch === '"') {
      current += ch;
      i += 1;
      while (i < body.length && body[i] !== '"') {
        current += body[i];
        if (body[i] === '\\') {
          i += 1;
          current += body[i] ?? '';
        }
        i += 1;
      }
      current += '"';
      continue;
    }

    if (ch === '{' || ch === '(') depth += 1;
    else if (ch === '}' || ch === ')') depth -= 1;

    // A new entry begins at a quote that starts at depth zero.
    if (depth === 0 && /\s/.test(ch)) {
      if (current.trim() && !current.trimEnd().endsWith('&') && peekStartsEntry(body, i)) {
        out.push(current.trim());
        current = '';
        continue;
      }
    }
    current += ch;
  }

  if (current.trim()) out.push(current.trim());
  return out;
}

/** True when the next non-space character opens a new `"name"` entry. */
function peekStartsEntry(body: string, from: number): boolean {
  for (let i = from; i < body.length; i++) {
    if (/\s/.test(body[i]!)) continue;
    return body[i] === '"';
  }
  return false;
}
